### ISSUE TITLE
依赖版本请教

### ISSUE THREAD

**Issue by publicHan** [Aaronphy/typings-mirrorx#1]
typings-mirrorx/package.json 里的依赖版本不设置为 * 的话 与creact react app 脚手架使用会出现问题?

**Comment by Aaronphy** [comment]
@publicHan 我觉得暂时把这个仓库的代码放到 node_modules 下。安装下依赖就好了

**Comment by Aaronphy** [comment]
@publicHan @types/mirrorx 已经发布啦。。可以使用了
